# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 03:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='hobby',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='student_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
